language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
script: grunt
after_success: grunt gh-pages:travis
env:
  global:
  - secure: Wjz736SETcAJS/j+ASteF93FWc2MZ0/3BtbA6go3C0OdXyRXf3548Gl1iNybUvnoYeFvekzNmQ82I7xEEj4R0i/nBRRhgnlDUIuo7j875EIp+FX0O6jsjpkg67tju11XAfISluQFK0fqgJeQ705tz2rr3nSK7HM1Xr9PA/+b+28=
branches:
  only:
    - master
